openapi: 3.0.0
info:
  title: idref
  version: '1.0'
  description: API de récupération des notices d'autorités du Système Universitaire de Documentation (Sudoc) de l'ESR
  contact:
    name: ABES
    url: 'https://stp.abes.fr/node/3?origine=idref'
    email: idref@abes.fr
  termsOfService: 'https://www.idref.fr/cgu.jsp'
  license:
    name: CeCILL
    url: 'https://cecill.info/index.en.html'
servers:
  - url: 'https://www.idref.fr'
paths:
  '/{PPN}':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
          headers:
            'content-type: application/rdf+xml;charset=UTF-8':
              schema:
                type: string
        '404':
          description: Not Found
      operationId: get-PPN
      parameters:
        - schema:
            type: string
            example: application/xml
            enum:
              - application/xml
              - application/rdf+xml
          in: header
          name: Accept
          description: Format demandé
      description: 'Renvoie une notice d''autorité correspondant à un PPN (identifiant), en MarcXML ou RDF, selon le header HTTP Accept'
  '/{PPN}.xml':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
        '404':
          description: Not found
      operationId: get-PPN-.xml
      description: 'Renvoie une notice d''autorité correspondant à un PPN (identifiant), au format XML'
      x-internal: false
      parameters: []
  '/{PPN}.rdf':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not found
      operationId: get-PPN-.rdf
      description: 'Renvoie une notice d''autorité correspondant à un PPN (identifiant), au format XML'
  '/services/biblio/{PPN}':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-services-biblio-PPN
      description: 'Renvoie la liste des références bibliographiques du Sudoc, liées à une notice d''autorité correspondant à un PPN (identifiant). Le format par défaut est MarcXML, mais on peut demander du JSON (par l''header HTTP ou en suffixant avec .json)'
      parameters:
        - $ref: '#/components/parameters/Accept'
  '/services/biblio/{PPN}.xml':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-services-biblio-PPN-.xml
      description: 'Renvoie la liste des références bibliographiques du Sudoc, liées à une notice d''autorité correspondant à un PPN (identifiant), en MarcXML'
  '/services/biblio/{PPN}.json':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-services-biblio-PPN-.json
      description: 'Renvoie la liste des références bibliographiques du Sudoc, liées à une notice d''autorité correspondant à un PPN (identifiant), en JSON'
  '/services/references/{PPN}':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-services-references-PPN
      description: 'Renvoie la liste des références bibliographiques, liées à une notice d''autorité correspondant à un PPN (identifiant). Le format par défaut est MarcXML, mais on peut demander du JSON (par l''header HTTP ou en suffixant avec .json)'
      parameters:
        - $ref: '#/components/parameters/Accept'
  '/services/references/{PPN}.xml':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-services-references-PPN-.xml
      description: 'Renvoie la liste des références bibliographiques, liées à une notice d''autorité correspondant à un PPN (identifiant), en MarcXML'
  '/services/references/{PPN}.json':
    parameters:
      - schema:
          type: string
        name: PPN
        in: path
        required: true
    get:
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-services-references-PPN-.json
      description: 'Renvoie la liste des références bibliographiques du Sudoc, liées à une notice d''autorité correspondant à un PPN (identifiant), en JSON'
  /Sru/Solr:
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-Sru-Solr
      description: |-
        Renvoie les informations sur les notices d'autorités du Système Universitaire de Documentation (Sudoc). 
        Il s'agit d'une API Solr 1.41 : https://svn.apache.org/repos/asf/lucene/solr/tags/release-1.4.1/site/tutorial.html#Querying+Data
      parameters:
        - schema:
            type: string
            example: '*:*'
          in: query
          name: q
          description: Critères de recherche
          required: true
        - schema:
            type: string
            example: ppn_z asc
          in: query
          name: sort
          description: Tri par index
        - schema:
            type: string
            example: '0'
          in: query
          name: start
          description: Démarre au nième résultat (pour pagination)
        - schema:
            type: string
            example: '10'
          in: query
          name: rows
          description: Nombre de documents maximum à retourner
        - schema:
            type: string
            example: '*'
          in: query
          name: fl
          description: Liste des indexes à retourner
        - schema:
            type: string
            enum:
              - json
              - xml
            example: json
          in: query
          name: wt
          description: 'Format retourné : XML (par défaut) ou JSON'
        - schema:
            type: string
            enum:
              - 'on'
              - 'off'
            example: 'on'
          in: query
          name: facet
          description: Active les facettes dans la réponse. A utiliser avec facet.field
        - schema:
            type: string
            example: recordtype_z
          in: query
          name: facet.field
          description: Index sur lequel avoir les facettes
components:
  schemas: {}
  securitySchemes: {}
  parameters:
    PPN:
      name: PPN
      in: path
      required: true
      schema:
        type: string
        pattern: '[0-9]{8}[0-9A-Z]{1}'
        minLength: 9
        maxLength: 9
        example: '139753753'
      description: Identifiant d'une notice d'autorité
    Accept:
      name: Accept
      in: header
      required: false
      schema:
        type: string
        enum:
          - application/xml
          - text/xml
          - application/json
          - text/json
        example: application/xml
      description: 'Format demandé (XML, JSON)'
