openapi: 3.0.0
info:
  title: sudoc
  version: '1.0'
  description: API de récupération des notices bibliographiques du Système Universitaire de Documentation (Sudoc) de l'ESR
  contact:
    name: ABES
    url: 'https://stp.abes.fr/node/3?origine=sudoc'
    email: sudoc@abes.fr
  termsOfService: 'http://psi-app-prod.sudoc.abes.fr/~c_psi/psi_gui/html/cgu.html'
  license:
    name: CeCILL
    url: 'https://cecill.info/index.en.html'
servers:
  - url: 'https://www.sudoc.fr'
paths:
  '/{PPN}':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-PPN
      parameters:
        - $ref: '#/components/parameters/Accept'
      description: 'Renvoie une notice bibliographique correspondant à un PPN (identifiant), au format RDF'
  '/{PPN}.rdf':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not found
      operationId: get-PPN-.rdf
      description: 'Renvoie une notice bibliographique correspondant à un PPN (identifiant), au format RDF'
  '/{PPN}.xml':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
        '404':
          description: Not found
      operationId: get-PPN-.xml
      description: 'Renvoie une notice bibliographique correspondant à un PPN (identifiant), au format MarcXML'
      x-internal: false
      parameters: []
  '/services/isbn2ppn/{ISBN}':
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-services-isbn2ppn
      description: |-
        Ce webservice renvoie un identifiant de notice bibliographique (PPN) à partir d'un ISBN valide

        <a href="http://documentation.abes.fr/sudoc/manuels/administration/aidewebservices/index.html#isbn2ppn" target=_blank>Lien vers la documentation</a>

        Exemple :

        https://www.sudoc.fr/services/isbn2ppn/2-07-037026-7
        https://www.sudoc.fr/services/isbn2ppn/2-07-037026-7,2-05-100362-9,201000535X
      parameters:
        - schema:
            type: string
            enum:
              - text/json
            example: text/json
          in: header
          name: Accept
          description: Format JSON
        - $ref: '#/components/parameters/format'
    parameters:
      - $ref: '#/components/parameters/ISBN'
  '/services/issn2ppn/{ISSN}':
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-issn2ppn
      description: |
        Ce webservice renvoie un identifiant de notice bibliographique (PPN) à partir d'un ISSN valide.
         
        <a href="http://documentation.abes.fr/sudoc/manuels/administration/aidewebservices/index.html#issn2ppn">Lien vers la documentation</a>

        Ex. : 

        <a href="https://www.sudoc.fr/services/issn2ppn/0774-3122" target="_blank">https://www.sudoc.fr/services/issn2ppn/0774-3122</a>

        <a href="https://www.sudoc.fr/services/issn2ppn/02672472,08581665,0296-2454,1242-9449,1242-9449&format=text/json" target=_blank>https://www.sudoc.fr/services/issn2ppn/02672472,08581665,0296-2454,1242-9449,1242-9449&format=text/json</a>
      parameters:
        - $ref: '#/components/parameters/Accept'
        - $ref: '#/components/parameters/format'
    parameters:
      - $ref: '#/components/parameters/ISSN'
  '/services/ean2ppn/{EAN}':
    parameters:
      - $ref: '#/components/parameters/EAN'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-services-ean2ppn-EAN
      description: |-
        Ce webservice renvoie un identifiant de notice bibliographique (PPN) à partir d'un EAN valide

        <a href="http://documentation.abes.fr/sudoc/manuels/administration/aidewebservices/index.html#ean2ppn" target=_blank>Lien vers la documentation</a>

        Exemple :

        https://www.sudoc.fr/services/ean2ppn/9782726600078
        https://www.sudoc.fr/services/ean2ppn/9782726600078,9782204015899,9782222024507
      parameters:
        - $ref: '#/components/parameters/format'
        - $ref: '#/components/parameters/Accept'
  '/services/frbn2ppn/{FRBN}':
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-services-frbn2ppn
      description: |-
        Ce webservice renvoie le PPN (identifiant d'une notice bibliographique dans le Sudoc) correspondant à une notice de la BnF (FRBNF).

        <a href="http://documentation.abes.fr/sudoc/manuels/administration/aidewebservices/index.html#MicroWebServiceFrbn2ppn" target=_blank>Lien vers la documentation</a>

        https://www.sudoc.fr/services/frbn2ppn/00000004X

        https://www.sudoc.fr/services/frbn2ppn/00000004X,00000051X
      parameters:
        - $ref: '#/components/parameters/Accept'
        - $ref: '#/components/parameters/format'
    parameters:
      - $ref: '#/components/parameters/FRBN'
  '/services/dnb2ppn/{DNB}':
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-services-dnb2ppn
      description: |-
        Ce webservice renvoie le PPN (identifiant d'une notice bibliographique dans le Sudoc) correspondant à une notice de la Deutsche Nationalbibliothek (DNB).

        <a href="http://documentation.abes.fr/sudoc/manuels/administration/aidewebservices/index.html#MicroWebServiceDnb2ppn" target=_blank>Lien vers la documentation</a>

        https://www.sudoc.fr/services/dnb2ppn/015130681

        https://www.sudoc.fr/services/dnb2ppn/015130681,100024797X
      parameters:
        - $ref: '#/components/parameters/format'
        - $ref: '#/components/parameters/Accept'
    parameters:
      - $ref: '#/components/parameters/DNB'
components:
  schemas: {}
  parameters:
    PPN:
      name: PPN
      in: path
      required: true
      schema:
        type: string
        pattern: '([0-9X]{9})(,$1)*'
        minLength: 9
        maxLength: 9
        example: '200479342'
      description: Identifiant d'une notice bibliographique
    Accept:
      name: Accept
      in: header
      required: false
      schema:
        type: string
        enum:
          - application/xml
          - text/xml
          - application/json
          - text/json
        example: application/xml
      description: 'Format demandé (XML, JSON)'
    ISBN:
      name: ISBN
      in: path
      required: true
      schema:
        type: string
        example: '2-07-037026-7,2-05-100362-9,201000535X'
      description: Numéro international normalisé du livre
    format:
      name: format
      in: query
      required: false
      schema:
        type: string
        enum:
          - text/json
        example: text/json
      description: Format demandé
    ISSN:
      name: ISSN
      in: path
      schema:
        type: string
        example: 1940-5758
        pattern: '(\d{4}\-?\d{3}(\d|x|X))(,$1)*'
        minLength: 8
      description: Identifiant international d'une publication en série
      required: true
    EAN:
      name: EAN
      in: path
      required: true
      schema:
        type: string
        pattern: '(\d{13})(,$1)*'
        example: '9782726600078'
        minLength: 13
      description: Identifiant commercial
    DNB:
      name: DNB
      in: path
      schema:
        type: string
        example: '015130681'
        pattern: '(\d{9})(,$1)*'
        minLength: 9
      description: Identifiant d'une notice dans le catalogue de la Deutsche NationalBibliothek
      required: true
    FRBN:
      name: FRBN
      in: path
      required: true
      schema:
        type: string
        pattern: '(\d{8,9}[0-9bcdfghjkmnpqrstvwxz])(,$1)*'
        minLength: 8
      description: Identifiant d'une notice dans le catalogue général de la BnF
