openapi: 3.0.0
info:
  title: sudoc
  version: '1.0'
  description: API de récupération des notices bibliographiques du Système Universitaire de Documentation (Sudoc) de l'ESR
  contact:
    name: ABES
    url: 'https://stp.abes.fr/node/3?origine=sudoc'
    email: sudoc@abes.fr
  termsOfService: 'http://psi-app-prod.sudoc.abes.fr/~c_psi/psi_gui/html/cgu.html'
  license:
    name: CeCILL
    url: 'https://cecill.info/index.en.html'
servers:
  - url: 'https://www.sudoc.fr'
paths:
  '/{PPN}':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-PPN
      parameters:
        - $ref: '#/components/parameters/Accept'
      description: 'Renvoie une notice bibliographique correspondant à un PPN (identifiant), au format RDF'
  '/{PPN}.rdf':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not found
      operationId: get-PPN-.rdf
      description: 'Renvoie une notice bibliographique correspondant à un PPN (identifiant), au format RDF'
  '/{PPN}.xml':
    parameters:
      - $ref: '#/components/parameters/PPN'
    get:
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
        '404':
          description: Not found
      operationId: get-PPN-.xml
      description: 'Renvoie une notice bibliographique correspondant à un PPN (identifiant), au format MarcXML'
      x-internal: false
      parameters: []
  '/services/isbn2ppn/{ISBN}':
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-services-isbn2ppn
      description: Ce webservice renvoie un identifiant de notice bibliographique (PPN) à partir d'un ISBN valide
      parameters:
        - schema:
            type: string
            enum:
              - text/json
            example: text/json
          in: header
          name: Accept
          description: Format JSON
        - $ref: '#/components/parameters/format'
    parameters:
      - $ref: '#/components/parameters/ISBN'
  '/services/issn2ppn/{ISSN}':
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties: {}
      operationId: get-issn2ppn
      description: |
        Ce webservice renvoie un identifiant de notice bibliographique (PPN) à partir d'un ISSN valide.
         
        <a href="http://documentation.abes.fr/sudoc/manuels/administration/aidewebservices/index.html#issn2ppn">Lien vers la documentation</a>

        Ex. : 

        <a href="https://www.sudoc.fr/services/issn2ppn/0774-3122" target="_blank">https://www.sudoc.fr/services/issn2ppn/0774-3122</a>

        <a href="https://www.sudoc.fr/services/issn2ppn/02672472,08581665,0296-2454,1242-9449,1242-9449&format=text/json" target=_blank>https://www.sudoc.fr/services/issn2ppn/02672472,08581665,0296-2454,1242-9449,1242-9449&format=text/json</a>
      parameters:
        - $ref: '#/components/parameters/Accept'
        - $ref: '#/components/parameters/format'
    parameters:
      - $ref: '#/components/parameters/ISSN'
components:
  schemas: {}
  parameters:
    PPN:
      name: PPN
      in: path
      required: true
      schema:
        type: string
        pattern: '[0-9]{8}[0-9A-Z]{1}'
        minLength: 9
        maxLength: 9
        example: '200479342'
      description: Identifiant d'une notice bibliographique
    Accept:
      name: Accept
      in: header
      required: false
      schema:
        type: string
        enum:
          - application/xml
          - text/xml
          - application/json
          - text/json
        example: application/xml
      description: 'Format demandé (XML, JSON)'
    ISBN:
      name: ISBN
      in: path
      required: true
      schema:
        type: string
        example: '2-07-037026-7,2-05-100362-9,201000535X'
      description: Numéro international normalisé du livre
    format:
      name: format
      in: query
      required: false
      schema:
        type: string
        enum:
          - text/json
        example: text/json
      description: Format demandé
    ISSN:
      name: ISSN
      in: path
      schema:
        type: string
        example: 1940-5758
        pattern: '\d{4}\-?\d{3}(\d|x|X)'
        minLength: 8
        maxLength: 9
      description: Identifiant international d'une publication en série
      required: true
