openapi: 3.0.0
info:
  title: theses
  version: '1.0'
  description: API de récupération des thèses de doctorat françaises
  contact:
    name: ABES
    url: 'https://stp.abes.fr/node/3?origine=thesesFr'
    email: theses@abes.fr
  termsOfService: 'http://www.theses.fr/conditions.html'
  license:
    name: Licence Ouverte Etalab
    url: 'https://www.etalab.gouv.fr/licence-ouverte-open-licence'
servers:
  - url: 'https://www.theses.fr'
paths:
  '/{NNT}/document':
    parameters:
      - $ref: '#/components/parameters/NNT'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-document
      description: |-
        Renvoie vers le document plein texte d'une thèse correspondant à un NNT (identifiant d'une thèse soutenue), pour peu que l'auteur ait fait le choix d'une diffusion ouverte.

        <a href="http://documentation.abes.fr/aidetheses/thesesfr/index.html#RecupererDonneesAPI" target=_blank>Lien vers la documentation</a>

        Exemple :

        http://theses.fr/2020GRALU020/document

        Tous droits réservés.
  '/{NNT_ou_numSujet}':
    parameters:
      - $ref: '#/components/parameters/NNT_ou_numSujet'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT
      description: |-
        Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant national des thèses soutenues) ou à un numsujet(identifiant d'un sujet de thèse en préparation), au format XML (TEF) ou RDF

        <a href="http://documentation.abes.fr/aidetheses/thesesfr/index.html#RecupererDonneesPageThese" target=_blank>Lien vers la documentation</a>

        Exemple :

        http://www.theses.fr/s237033

        http://www.theses.fr/2007PA112182


        Données disponibles sous <a href="https://www.etalab.gouv.fr/licence-ouverte-open-licence" target=_blank>Licence Ouverte / Open Licence de l’État élaborée par la mission Etalab</a>. La récupération et la réutilisation des données est libre et gratuite sous réserve de l’indication de leur date de récupération et de la mention de leur source.
      parameters:
        - $ref: '#/components/parameters/Accept'
  '/{NNT_ou_numSujet}.rdf':
    parameters:
      - $ref: '#/components/parameters/NNT_ou_numSujet'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-.rdf
      description: |-
        Renvoie les métadonnées de la thèse correspondant à un NNT (thèse soutenue) ou à un numSujet (thèse en cours), au format RDF

        <a href="http://documentation.abes.fr/aidetheses/thesesfr/index.html#RecupererDonneesPageThese" target=_blank>Lien vers la documentation</a>

        Exemple :

        http://www.theses.fr/s237033.rdf

        http://www.theses.fr/2007PA112182.rdf

        Données disponibles sous <a href="https://www.etalab.gouv.fr/licence-ouverte-open-licence" target=_blank>Licence Ouverte / Open Licence de l’État élaborée par la mission Etalab</a>. La récupération et la réutilisation des données est libre et gratuite sous réserve de l’indication de leur date de récupération et de la mention de leur source.
  '/{NNT_ou_numSujet}.xml':
    parameters:
      - $ref: '#/components/parameters/NNT_ou_numSujet'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-.xml
      description: |-
        Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant d'une thèse soutenue) ou à un numSujet(identifiant d'une thèse en préparation), au format XML (TEF)

        Exemple :

        http://www.theses.fr/s237033.xml

        http://www.theses.fr/2007PA112182.xml

        Données disponibles sous <a href="https://www.etalab.gouv.fr/licence-ouverte-open-licence" target=_blank>Licence Ouverte / Open Licence de l’État élaborée par la mission Etalab</a>. La récupération et la réutilisation des données est libre et gratuite sous réserve de l’indication de leur date de récupération et de la mention de leur source.
  '/{NNT}.ris':
    parameters:
      - name: NNT
        in: path
        schema:
          type: string
          pattern: '\d{4}[A-Z]{2}[0-9A-Z]{2}[0-9A-Z]{4}'
          minLength: 12
          maxLength: 12
          example: 2018LAROS028
        description: Numéro National de Thèse
        required: true
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-.ris
      description: |-
        Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant), au format RIS

        Exemple :

        http://www.theses.fr/2007PA112182.ris

        Données disponibles sous <a href="https://www.etalab.gouv.fr/licence-ouverte-open-licence" target=_blank>Licence Ouverte / Open Licence de l’État élaborée par la mission Etalab</a>. La récupération et la réutilisation des données est libre et gratuite sous réserve de l’indication de leur date de récupération et de la mention de leur source.
  '/{NNT_ou_numSujet}.bib':
    parameters:
      - schema:
          type: string
        name: NNT_ou_numSujet
        in: path
        required: true
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-.bib
      description: 'Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant), au format BibTeX'
  /fr/:
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-fr
      description: |-
        Renvoie les informations sur les thèses de doctorat françaises. 
        Il s'agit d'une API Solr 1.41 proxifiée : le paramètre "wt" est remplacé par "format" et accepte csv et atom, comme formats supplémentaires.

        <a href="https://svn.apache.org/repos/asf/lucene/solr/tags/release-1.4.1/site/tutorial.html#Querying+Data" target="_blank">Doc API Solr 1.41</a> 
      parameters:
        - schema:
            type: string
            example: '*:*'
          in: query
          name: q
          description: Critères de recherche
          required: true
        - schema:
            type: string
            enum:
              - avancee
            example: avancee
          in: query
          name: type
          description: 'Obligatoire pour utiliser l''API : type=avancee'
          required: true
        - schema:
            type: string
            enum:
              - json
              - xml
              - csv
              - atom
            example: xml
          in: query
          name: format
          description: 'Format retourné : JSON, XML, CSV, ATOM'
          required: true
        - schema:
            type: string
            example: num asc
          in: query
          name: sort
          description: Tri par index
        - schema:
            type: string
            example: '0'
          in: query
          name: start
          description: Démarre au nième résultat (pour pagination)
        - schema:
            type: string
            example: '30'
          in: query
          name: rows
          description: Nombre de documents maximum à retourner
        - schema:
            type: string
            example: '*'
          in: query
          name: fl
          description: Liste des indexes à retourner
        - schema:
            type: string
            enum:
              - 'on'
              - 'off'
            example: 'on'
          in: query
          name: facet
          description: Active les facettes dans la réponse. A utiliser avec facet.field
        - schema:
            type: string
            example: discipline
          in: query
          name: facet.field
          description: Index sur lequel avoir les facettes
      x-internal: true
components:
  schemas: {}
  parameters:
    NNT:
      name: NNT
      in: path
      schema:
        type: string
        pattern: '\d{4}[A-Z]{2}[0-9A-Z]{2}[0-9A-Z]{4}'
        minLength: 12
        maxLength: 12
        example: 2018LAROS028
      description: Numéro National de Thèse
      required: true
    Accept:
      name: Accept
      in: header
      required: false
      schema:
        type: string
        enum:
          - application/xml
          - application/rdf+xml
        example: application/xml
      description: 'Format demandé (XML, RDF)'
    NNT_ou_numSujet:
      name: NNT_ou_numSujet
      in: path
      schema:
        type: string
        example: 2007PA112182
        pattern: '(\d{4}[A-Z]{2}[0-9A-Z]{6})|(s\d{1,7})'
      description: Identifiant d'une thèse soutenue (NNT) ou en cours (numSujet)
      required: true
  securitySchemes: {}
