openapi: 3.0.0
info:
  title: theses
  version: '1.0'
  description: API de récupération des thèses de doctorat françaises
  contact:
    name: ABES
    url: 'https://stp.abes.fr/node/3?origine=thesesFr'
    email: theses@abes.fr
  termsOfService: 'http://www.theses.fr/conditions.html'
  license:
    name: CeCILL
    url: 'https://cecill.info/index.en.html'
servers:
  - url: 'https://www.theses.fr'
paths:
  '/{NNT}/document':
    parameters:
      - $ref: '#/components/parameters/NNT'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-document
      description: Renvoie le document plein texte d'une thèse correspondant à un NNT (identifiant)
  '/{NNT}':
    parameters:
      - $ref: '#/components/parameters/NNT'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT
      description: 'Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant), au format XML (TEF) ou RDF'
      parameters:
        - $ref: '#/components/parameters/Accept'
  '/{numSujet}':
    parameters:
      - $ref: '#/components/parameters/numSujet'
    get:
      summary: ''
      tags: []
      responses: {}
      operationId: get-numSujet
      description: 'Renvoie les métadonnées du sujet de thèse en préparation correspondant à un numSujet (identifiant), au format XML (TEF) ou RDF'
      parameters:
        - $ref: '#/components/parameters/Accept'
  '/{NNT}.rdf':
    parameters:
      - $ref: '#/components/parameters/NNT'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-.rdf
      description: 'Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant), au format RDF'
  '/{NNT}.xml':
    parameters:
      - $ref: '#/components/parameters/NNT'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-.xml
      description: 'Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant), au format XML (TEF)'
  '/{NNT}.ris':
    parameters:
      - $ref: '#/components/parameters/NNT'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-.ris
      description: 'Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant), au format RIS'
  '/{NNT}.bib':
    parameters:
      - $ref: '#/components/parameters/NNT'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-.bib
      description: 'Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant), au format BibTeX'
  '/{numSujet}.rdf':
    parameters:
      - $ref: '#/components/parameters/numSujet'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-numSujet-.rdf
      description: 'Renvoie les métadonnées du sujet de thèse en préparation correspondant à un numSujet (identifiant), au format RDF'
  '/{numSujet}.xml':
    parameters:
      - $ref: '#/components/parameters/numSujet'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-numSujet-.xml
      description: 'Renvoie les métadonnées du sujet de thèse en préparation correspondant à un numSujet (identifiant), au format XML (TEF)'
  '/{numSujet}.ris':
    parameters:
      - $ref: '#/components/parameters/numSujet'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-numSujet-.ris
      description: 'Renvoie les métadonnées du sujet de thèse en préparation correspondant à un numSujet (identifiant), au format RIS'
  '/{numSujet}.bib':
    parameters:
      - $ref: '#/components/parameters/numSujet'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-numSujet-.bib
      description: 'Renvoie les métadonnées du sujet de thèse en préparation correspondant à un numSujet (identifiant), au format BiTeX'
components:
  schemas: {}
  parameters:
    NNT:
      name: NNT
      in: path
      required: true
      schema:
        type: string
        pattern: 'd{4}[A-Z]{2}[0-9A-Z]{2}[0-9A-Z]{4}'
        minLength: 12
        maxLength: 12
        example: 2018LAROS028
      description: Numéro National de Thèse
    numSujet:
      name: numSujet
      in: path
      required: true
      schema:
        type: string
        pattern: s\d*
      description: Numéro de sujet de thèse en préparation
    Accept:
      name: Accept
      in: header
      required: false
      schema:
        type: string
        enum:
          - application/xml
          - application/rdf+xml
      description: 'Format demandé (XML, RDF)'
