openapi: 3.0.0
info:
  title: theses
  version: '1.0'
  description: API de récupération des thèses de doctorat françaises
  contact:
    name: ABES
    url: 'https://stp.abes.fr/node/3?origine=thesesFr'
    email: theses@abes.fr
  termsOfService: 'http://www.theses.fr/conditions.html'
  license:
    name: CeCILL
    url: 'https://cecill.info/index.en.html'
servers:
  - url: 'https://www.theses.fr'
paths:
  '/{NNT}/document':
    parameters:
      - $ref: '#/components/parameters/NNT'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-document
      description: Renvoie le document plein texte d'une thèse correspondant à un NNT (identifiant)
  '/{NNT}':
    parameters:
      - $ref: '#/components/parameters/NNT'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT
      description: 'Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant), au format XML (TEF) ou RDF'
      parameters:
        - $ref: '#/components/parameters/Accept'
  '/{numSujet}':
    parameters:
      - $ref: '#/components/parameters/numSujet'
    get:
      summary: ''
      tags: []
      responses: {}
      operationId: get-numSujet
      description: 'Renvoie les métadonnées du sujet de thèse en préparation correspondant à un numSujet (identifiant), au format XML (TEF) ou RDF'
      parameters:
        - $ref: '#/components/parameters/Accept'
  '/{NNT}.rdf':
    parameters:
      - $ref: '#/components/parameters/NNT'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-.rdf
      description: 'Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant), au format RDF'
  '/{NNT}.xml':
    parameters:
      - $ref: '#/components/parameters/NNT'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-.xml
      description: 'Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant), au format XML (TEF)'
  '/{NNT}.ris':
    parameters:
      - $ref: '#/components/parameters/NNT'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-.ris
      description: 'Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant), au format RIS'
  '/{NNT}.bib':
    parameters:
      - $ref: '#/components/parameters/NNT'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-NNT-.bib
      description: 'Renvoie les métadonnées de la thèse correspondant à un NNT (identifiant), au format BibTeX'
  '/{numSujet}.rdf':
    parameters:
      - $ref: '#/components/parameters/numSujet'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-numSujet-.rdf
      description: 'Renvoie les métadonnées du sujet de thèse en préparation correspondant à un numSujet (identifiant), au format RDF'
  '/{numSujet}.xml':
    parameters:
      - $ref: '#/components/parameters/numSujet'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-numSujet-.xml
      description: 'Renvoie les métadonnées du sujet de thèse en préparation correspondant à un numSujet (identifiant), au format XML (TEF)'
  '/{numSujet}.ris':
    parameters:
      - $ref: '#/components/parameters/numSujet'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-numSujet-.ris
      description: 'Renvoie les métadonnées du sujet de thèse en préparation correspondant à un numSujet (identifiant), au format RIS'
  '/{numSujet}.bib':
    parameters:
      - $ref: '#/components/parameters/numSujet'
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-numSujet-.bib
      description: 'Renvoie les métadonnées du sujet de thèse en préparation correspondant à un numSujet (identifiant), au format BiTeX'
  /fr/:
    get:
      summary: ''
      tags: []
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      operationId: get-fr
      description: |-
        Renvoie les informations sur les thèses de doctorat françaises. 
        Il s'agit d'une API Solr 1.41 proxifiée : le paramètre "wt" est remplacé par "format" et accepte csv et atom, comme formats supplémentaires.

        Doc API Solr 1.41 : https://svn.apache.org/repos/asf/lucene/solr/tags/release-1.4.1/site/tutorial.html#Querying+Data 
      parameters:
        - schema:
            type: string
            example: zola
          in: query
          name: q
          description: Critères de recherche
          required: true
        - schema:
            type: string
            enum:
              - avancee
            example: avancee
          in: query
          name: type
          description: 'Obligatoire pour utiliser l''API : type=avancee'
          required: true
        - schema:
            type: string
            enum:
              - json
              - xml
              - csv
              - atom
            example: xml
          in: query
          name: format
          description: 'Format retourné : JSON, XML, CSV, ATOM'
          required: true
        - schema:
            type: string
            example: num asc
          in: query
          name: sort
          description: Tri par index
        - schema:
            type: string
            example: '0'
          in: query
          name: start
          description: Démarre au nième résultat (pour pagination)
        - schema:
            type: string
            example: '30 '
          in: query
          name: rows
          description: Nombre de documents maximum à retourner
        - schema:
            type: string
            example: '*'
          in: query
          name: fl
          description: Liste des indexes à retourner
        - schema:
            type: string
            enum:
              - 'on'
              - 'off'
            example: 'on'
          in: query
          name: facet
          description: Active les facettes dans la réponse. A utiliser avec facet.field
        - schema:
            type: string
            example: discipline
          in: query
          name: facet.field
          description: Index sur lequel avoir les facettes
components:
  schemas: {}
  parameters:
    NNT:
      name: NNT
      in: path
      required: true
      schema:
        type: string
        pattern: 'd{4}[A-Z]{2}[0-9A-Z]{2}[0-9A-Z]{4}'
        minLength: 12
        maxLength: 12
        example: 2018LAROS028
      description: Numéro National de Thèse
    numSujet:
      name: numSujet
      in: path
      required: true
      schema:
        type: string
        pattern: s\d*
        example: s279863
      description: Numéro de sujet de thèse en préparation
    Accept:
      name: Accept
      in: header
      required: false
      schema:
        type: string
        enum:
          - application/xml
          - application/rdf+xml
        example: application/xml
      description: 'Format demandé (XML, RDF)'
